development: &development
  adapter: mysql2
  host: localhost
  username: ukirama
  password: "123"
  database: resto_terserah_development

test: &test
  adapter: mysql2
  host: localhost
  username: ukirama
  password: "123"
  database: resto_terserah_test

production: &production
  adapter: mysql2
  host: localhost
  database: your_production_database
  username: your_production_database_login
  password: your_production_database_password
